FROM node:21-alpine

RUN apt-get update -y

RUN apt-get install tzdata -y

WORKDIR /app

COPY package*.json ./

RUN npm install --force
    

COPY . .

RUN npm run build

EXPOSE 5373

CMD ["npm", "start"]
